Update: Start using https://davidbalishyan.github.io/board.bash

diff --git a/scripts/net b/scripts/net
--- a/scripts/net
+++ b/scripts/net
@@ -10,26 +10,14 @@
 # # Contributors
 # - Dave Eddy <ysap@daveeddy.com>
 # - Ilias Moulas <ilias@moulas.dev>
+# - Me (David Balishya) <davidbalishyan12@gmail.com>
+
+source "$(dirname "$0")/board.bash"
 
 declare -A DATA=()
 
-if [[ -z $NO_COLOR ]]; then
-	COLOR=$'\e[36m'
-	DIM=$'\e[2m'
-	RST=$'\e[0m'
-else
-	COLOR=
-	DIM=
-	RST=
-fi
-
-TITLE_FMT="$DIM%15s %15s %15s %15s$RST\\n"
-DATA_FMT="$COLOR%15s$RST %15s %15s %15s\\n"
-
-fatal() {
-	echo '[FATAL]' "$@" >&2
-	exit 1
-}
+TITLE_FMT="$DIM%15s %15s %15s %15s$RESET\\n"
+DATA_FMT="$CYAN%15s$RESET %15s %15s %15s\\n"
 
 format-bits() {
 	local bits=$1
@@ -48,15 +36,12 @@ process-iface() {
 	local rx_bytes=$2
 	local tx_bytes=$3
 
-	# check if we've seen this interface before
 	local old=${DATA[$iface]}
 
-	# store the new data no matter what
 	DATA[$iface]="$rx_bytes $tx_bytes"
 
 	local old_rx_bytes old_tx_bytes
 
-	# initialize old values to 0 if we haven't seen this interface before
 	if [[ -z $old ]]; then
 		old_rx_bytes=0
 		old_tx_bytes=0
@@ -79,30 +64,18 @@ process-iface() {
 	printf "$DATA_FMT" "$iface" "$rx" "$tx" "$total"
 }
 
-deinit-term() {
-	printf '\e[?1049l' # disable alternate buffer
-	printf '\e[?25h' # show the cursor
-}
-
-init-term() {
-	printf '\e[?1049h' # enable alternate buffer
-	printf '\e[?25l' # hide the cursor
-	printf '\e[H' # move the cursor home
-}
-
 main() {
-	trap deinit-term EXIT
-	init-term
+	trap cursor_show EXIT
+	cursor_hide
+	clear_screen
 
 	while true; do
-		printf '\e[H' # move the cursor home
+		printf '\e[H'
 
-		# read /proc file
 		local -a lines
 		mapfile -t -s 2 lines < /proc/net/dev \
-		    || fatal 'failed to read proc device'
+		    || die 'failed to read proc device'
 
-		# loop each line in the file
 		echo
 		printf "$TITLE_FMT" interface receive transmit total
 
